# Generated by Django 6.0.6 on 2026-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('sens', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=8, verbose_name='Sens')),
            ],
            options={
                'verbose_name': "Catégorie d'opération",
                'verbose_name_plural': "Catégories d'opérations",
                'ordering': ['sens', 'libelle'],
            },
        ),
    ]
