# Generated by Django 6.0.6 on 2026-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur')], max_length=11, verbose_name='Type')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom ou raison sociale')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['type', 'nom'],
            },
        ),
    ]
