# Generated by Django 6.0.6 on 2026-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='activite',
            field=models.CharField(blank=True, help_text='Ex. : Commerce de détail, BTP, Restauration, Transport…', max_length=120, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Personne à contacter'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
