# Generated by Django 6.0.6 on 2026-06-08 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('description', models.TextField(verbose_name='Description / Libellé')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('categorie', models.ForeignKey(limit_choices_to={'sens': 'DEPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.categorieoperation', verbose_name='Catégorie')),
                ('partenaire', models.ForeignKey(blank=True, limit_choices_to={'type': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='partners.partenaire', verbose_name='Fournisseur')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-date_saisie'],
            },
        ),
    ]
